# Generated by Django 6.0 on 2025-12-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='limit_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Limite Disponível'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='limit_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite Total'),
        ),
    ]
