# Generated by Django 6.0 on 2025-12-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
