# Generated by Django 6.0 on 2025-12-06 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_creditcard_limit_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Base')),
                ('due_day', models.IntegerField(verbose_name='Dia de Vencimento')),
                ('category', models.CharField(choices=[('HOUSING', 'Moradia'), ('UTILITIES', 'Contas (Luz/Água)'), ('INTERNET', 'Internet/TV'), ('FOOD', 'Alimentação'), ('HEALTH', 'Saúde'), ('EDUCATION', 'Educação'), ('LEISURE', 'Lazer'), ('OTHER', 'Outros')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bills', to='core.house')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.recurringbill'),
        ),
    ]
