# Generated by Django 6.0 on 2025-12-06 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='house',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.house'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reference_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(default='un', max_length=10),
        ),
    ]
