# Generated by Django 6.0 on 2025-12-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction_house_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Qtd Mínima'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reference_date',
            field=models.DateField(help_text='Data de referência'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(default='un', help_text='kg, L, un, cx', max_length=10),
        ),
    ]
