# Generated by Django 6.0 on 2025-12-06 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_invoice_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Médio'),
        ),
        migrations.AddField(
            model_name='product',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.house'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Produto'),
        ),
    ]
