# Generated by Django 6.0 on 2025-12-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_estimated_price_product_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Qtd Mínima Padrão'),
        ),
        migrations.AlterField(
            model_name='product',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(default='un', max_length=10),
        ),
    ]
