# Generated by Django 6.0 on 2025-12-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_min_quantity_alter_product_estimated_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='discount_unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço c/ Desc (Un)'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='real_unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Real (Un)'),
        ),
    ]
