# Generated by Django 6.0 on 2025-12-11 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_total_price_transactionitem_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionitem',
            old_name='value',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='description',
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
